# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movida' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movida

pod 'Firebase/Analytics'
pod 'TextFieldEffects'
pod 'LGButton'
pod 'SwiftIconFont'
pod 'FirebaseAuth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'FaveButton'


  target 'MovidaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovidaUITests' do
    # Pods for testing
  end

end
